"""empty message

Revision ID: 6099f2caadc0
Revises: 
Create Date: 2018-12-08 13:08:52.732329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6099f2caadc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpio_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status_enum', sa.String(length=128), nullable=True),
    sa.Column('status_numeric', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpio_task_name'), 'gpio_task', ['name'], unique=False)
    op.create_table('run_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_time_end_time'), 'run_time', ['end_time'], unique=False)
    op.create_index(op.f('ix_run_time_start_time'), 'run_time', ['start_time'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('water_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_f', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_temp')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_run_time_start_time'), table_name='run_time')
    op.drop_index(op.f('ix_run_time_end_time'), table_name='run_time')
    op.drop_table('run_time')
    op.drop_index(op.f('ix_gpio_task_name'), table_name='gpio_task')
    op.drop_table('gpio_task')
    # ### end Alembic commands ###
