"""empty message

Revision ID: 6197f3616fbb
Revises: 4911128bb4a1
Create Date: 2018-12-08 12:15:12.817697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6197f3616fbb'
down_revision = '4911128bb4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_times_end_time'), 'run_times', ['end_time'], unique=False)
    op.create_index(op.f('ix_run_times_start_time'), 'run_times', ['start_time'], unique=False)
    op.create_table('water_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_f', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transaction')
    op.add_column('gpio_task', sa.Column('create_datetime', sa.DateTime(), nullable=True))
    op.drop_column('gpio_task', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpio_task', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.drop_column('gpio_task', 'create_datetime')
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.Column('value_numeric', sa.FLOAT(), nullable=True),
    sa.Column('value_enum', sa.VARCHAR(length=128), nullable=True),
    sa.Column('ts', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('water_temp')
    op.drop_index(op.f('ix_run_times_start_time'), table_name='run_times')
    op.drop_index(op.f('ix_run_times_end_time'), table_name='run_times')
    op.drop_table('run_times')
    # ### end Alembic commands ###
