"""empty message

Revision ID: 9749a15f98ee
Revises: 6099f2caadc0
Create Date: 2018-12-24 18:21:30.016785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9749a15f98ee'
down_revision = '6099f2caadc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_f', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('box_temp')
    # ### end Alembic commands ###
